### ISSUE TITLE
Possibility for endpoint to get data

### ISSUE THREAD

**Issue by takoz53** [grumd/osu-pps#37]
Would you consider to make an endpoint to get data? E.g. 
https://osu-pps.com/#/osu/maps?name="Sotarks"&ppMin=300&ppMax=400&ModCombinations=2&...
which yields back a JSON file with x amount of maps within criteria.
Parameters are basically filters found on the website, so it would be filled by those. (ModCombinations could be for instance &HD=yes&DT=any) as well.
To make it less power consuming it would yield back x amount, and the endpoint might allow to get x amount of other maps within that criteria, e.g. 
https://osu-pps.com/#/osu/maps?name="Sotarks"&ppMin=300&ppMax=400&ModCombinations=2 **&page=2**

JSON yields back:
{
**foundMaps**: amount of beatmaps found
**pages**: foundMaps / pagesize
**List of objects {**
**mapname**: "mapname"
**url**: "urltoBeatmap"
**approxPP**: pp
**modCombinatons**: "HD, DT, HR" - or combination (1,2,4,8...)
**length**: in seconds (so user can format themselves)
**difficultyNormal**: NM calculation
**difficultyCalculated**: Mod Combination calculation (If this is possible and not too power consuming)
**overweightnessPlaycount**:  overweightness by playcount
**overweightnessAdjusted**:  overweightness by adjusted
**overweightnessAge**:  overweightness by age
**overweightnessTotal**:  overweightness by total
}

}

**Comment by takoz53** [comment]
Would really appreciate it if you considered it. Could make good use out of this! c:

**Comment by grumd** [comment]
@takoz53 
All the data used by my website is in this branch and this folder in json format (some is in csv to save space)
https://github.com/grumd/osu-pps/tree/data/data

**Comment by takoz53** [comment]
Thank you a lot; If I could ask a few questions, since you coded this for your own purpose and the naming is a bit weird;
Could you explain the datastructure a bit so I could get started.

Why is there "mappers" to begin with? What is favored mappers and why is their maps in a special folder? Exact same question with "pp-mappers". I mean I understand they're the main way to get PP usually.

For diffs.csv If I understood correctly, it would just be all the difficulties with specific PP or so?
m,b,x,pp99,adj,v,s,l,d,p,h,appr_h doesn't make sense to me though.
Does this list also get updated with new maps or is it always the same data? (Can I download and keep it or do I have to get the data over and over again?)
To get all the information of one map, do you basically connect mapset.csv with diffs.csv to get all the information out?

If I understand correctly, metadata.json is only there to see if your data has been updated so I have to redownload everything, is that correct?

Sorry for many questions. In hopes that I have no other questions and in hopes that you might answer this :P thank you

**Comment by grumd** [comment]
I'll leave a short guidy thing here then

1. `data/mappers` is for data that's used by "mappers" page on the website
`pp-mappers.json` is data for pp mappers list: https://osu-pps.com/#/osu/mappers/pp
`favored-mappers.json` is data for quality mappers list: https://osu-pps.com/#/osu/mappers/fav
2. `data/ranking` is for https://osu-pps.com/#/osu/rankings
tbh the data here is "compressed" to save some space so might be hard to get reliable info from here
3. `data/maps` is the main stuff where data about overweightness is.
`mapsets.csv` with data about mapsets
columns are "art,t,bpm,g,ln,s" which corresponds to:
artist, title, bpm, genre, length, set id
`diffs.csv` with data about beatmaps
columns are "m,b,x,pp99,adj,v,s,l,d,p,h,appr_h" which corresponds to:
mods, beatmap id, overweightness, pp, adjustment factor, version name, set id, hit length, difficulty, passcount, playtime (hours), hours since approved

if you really need uncompressed data from `data/ranking`, you'll have to run `update-scripts/scheduler.js`, it generates way more data some of which is more readable. i just can't push it to github because files are too big

also yes, all data from that folder is updated every 1-2 days (when my script doesn't crash)

**Comment by grumd** [comment]
I'll be honest when people come here asking if they can use some of the internals I'm like AAAAAAAA please don't look I'm naked. This code is so old and shitty lmao

**Comment by takoz53** [comment]
I have read your description about the project, so I totally feel you. I am so thankful for the help instead. This might be hell if I couldnt ask you questions instead. I wont need ranked data, so I most likely wont run that scirpt. I will most likely only need that farm stuff so data/ranking, so thank you a lot for the information!!

**Comment by takoz53** [comment]
Hello, got a question again! mapset.csv has only flat numbers for "length", which makes no sense to me. "Ai no Sukima" e.g. should not be flat 3. MIMIs Ai no Sukima is either 1.07 or 3.37, so I am a bit lost here. Could you elaborate?

Also, approved hours for entry:
0,1988753,15024.27,231.21,3250,Radiance,952409,66,5.82,1935810,20205,432331
432331 means it has to be approved like 600 months ago. I don't quite understand appr_h yet. If you could elaborate this as well, I'd be glad.

**Comment by grumd** [comment]
@takoz53 

oh, sorry

`ln` is not length, it's `language_id` - language of the mapset

`appr_h` is hours since unix start time, so hours since 1970-01-01 00:00:00

from `update-scripts/fetch-map-info.js`
![image](https://user-images.githubusercontent.com/5869818/129453351-9803099c-db52-4178-ba2b-b8efc8da8b6a.png)
