### ISSUE TITLE
Hard to contribute / add separate data branch

### ISSUE THREAD

**Issue by WebFreak001** [grumd/osu-pps#8]
It's difficult contributing to this project right now as the master branch keeps getting force-pushed with every data update. It breaks the history or working changes of contributors because of inconvenient pulls that need to be done to keep the local changes but receive upstream commits. You can also see this issue in the [pull requests page](https://github.com/grumd/osu-pps/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed) as nearly all PRs get closed without being merged but the commits or functionality still kind of make it in, which might be encouraged by the comments/update history being flooded with force-pushes into the branch and making the auto merge button hard to use.

Could a separate dedicated `data` branch (or similar) without any code be used instead for pushing the data? You could also no longer force the push and this way keep a history of PP data which might be very interesting for data analysis too. Simply adding a new line character at the end of every song would also immensely help git with keeping track of changes and allow for parallel JSON parsing of each line.

**Comment by grumd** [comment]
@WebFreak001 if you wanna contribute, contribute to `develop` branch. `master` is there only for data updates. I'm usually developing in `develop`, then when I want to update the website, I run `npm run deploy` from `develop` branch and `gh-pages` gets updated. When I want to update my server, I merge `develop` into `master`, pull `master` on my server and restart the update script.

I will keep force-pushing to `master` because if I didn't, git history would get HEAVILY flooded with 50Mb updates every couple of days. I'm pretty sure this repository would get banned or something. I think there's a limit on how much data you can store in the history. So I'm just force-pushing to keep it sane. Git wasn't meant to be used as a free data storage for your server, that's why I'm hacking here a bit.

Just use `develop`.

**Comment by grumd** [comment]
Added a README.md to help newcomers.
